### ISSUE TITLE
PDF "Locker" 

### ISSUE THREAD

**Issue by rcasad** [Treverr/inSparkle#102]
Digital filing cabinet for storing and accessing PDFs of important catalogs

**Comment by Treverr** [comment]
PDF Locker Complete.

Abilities:
Open PDF's into inSparkle, these will autosave into the PDF Locker
Delete from PDF Locker
View PDF's in PDF Locker

**Comment by Treverr** [comment]
TODO: Pop to View of PDF when importing a new one.

**Comment by Treverr** [comment]
Added function : Rename a PDF
