### ISSUE TITLE
Edit button invoke checkbox for mass delete in SOI

### ISSUE THREAD

**Issue by Treverr** [Treverr/inSparkle#11]
Ability to mass delete.

@rcasad : select all? or individual selection?

**Comment by rcasad** [comment]
Both?

**Comment by rcasad** [comment]
@Treverr both?

**Comment by Treverr** [comment]
Ability to multi select completed.

**Comment by Treverr** [comment]
No SELECT ALL button at this time. Screen is too crowded.

**Comment by Treverr** [comment]
@rcasad confirm and approve.
