### ISSUE TITLE
Emails

### ISSUE THREAD

**Issue by rbrtcsd** [Treverr/inSparkle#13]
Multiple emails sent when editing/adding a customer (to Robert) 

I have noticed (and it may be a fluke) that it seems to only send one when editing from the customer lookup screen, 3 when editing in POCs, and possibly 2 when editing from messages. 

If its not possible/not easy to repair this, we may choose to shut the emails off (considering the emails are only intended to prevent inaccuracies when uploading customers to Parse, but thats unavailable right now)

**Comment by Treverr** [comment]
Resolved. Cloud code in Parse Server is having issues, this code has been move to the app for our backend Mail to accept the request from the app itself, shouldn't be any change in the UX. Tested and confirmed it is now only sending one email.

**Comment by Treverr** [comment]
I have disabled most emails for time away at this time, if this is something you like/want, I will update them.
