### ISSUE TITLE
Re-Enroll

### ISSUE THREAD

**Issue by Treverr** [Treverr/inSparkle#16]
It looks like you need to re-enroll some devices with the users.

Store iPad 1
Store iPad 2
Time Clock
Marti's iPad Pro
iPhone (Toms?)
iPad Pro (Toms?)
Service iPad 1

These are not enrolled with a user but are enrolled with the system still

If you get a chance please re-enroll them.

Thank you!

**Comment by Treverr** [comment]
Scratch the above. All devices need re-enrolled.

**Comment by rbrtcsd** [comment]
This is almost complete - Just need to get the Service iPad and the time clock completed
