### ISSUE TITLE
Pull from Customer Database

### ISSUE THREAD

**Issue by Treverr** [Treverr/inSparkle#19]

**Comment by Treverr** [comment]
Tableview is now pulling and displaying customer database properly.

**Comment by Treverr** [comment]
Added a way to add a new customer.

Cell at the top of the screen will display "Add Customer"

![simulator screen shot dec 12 2015 4 39 36 pm](https://cloud.githubusercontent.com/assets/5624521/11764040/f1d7e840-a0ee-11e5-9529-a2b983a74ff2.png)

**Comment by Treverr** [comment]
Add a magnifying glass next to "Customer Name" field for searches.

**Comment by Treverr** [comment]
Added search button : 
![simulator screen shot dec 13 2015 2 02 22 am](https://cloud.githubusercontent.com/assets/5624521/11765944/9df6d62e-a13d-11e5-87c0-b9a85654cace.png)

**Comment by Treverr** [comment]
Added EDIT button to customer cell: 

![simulator screen shot dec 13 2015 2 03 23 am](https://cloud.githubusercontent.com/assets/5624521/11765946/b78cf1c2-a13d-11e5-9043-efaec5bfa6b9.png)

**Comment by Treverr** [comment]
Selecting customer to autofill data on the add to schedule screen is still WIP, most likely will cause a crash at this time.

**Comment by rcasad** [comment]
Please change magnifying glass icon to grey and make slightly smaller.

**Comment by Treverr** [comment]
Completed!

**Comment by Treverr** [comment]
TODO : Complete save to database

**Comment by rcasad** [comment]
@Treverr aside from the iPad crashing, is this complete?

**Comment by Treverr** [comment]
Correct. I believe this is complete.

**Comment by rcasad** [comment]
@Treverr Do Is the issue we found with the edit/add screens maintaining information considered part of this or do I complete this?

**Comment by Treverr** [comment]
@rcasad That was fixed :)
