### ISSUE TITLE
Add to Schedule - ? mark for help

### ISSUE THREAD

**Issue by Treverr** [Treverr/inSparkle#27]
A pop up over explaining what something is (Aquadoor) etc

**Comment by Treverr** [comment]
@rcasad which ones should have this?

**Comment by rcasad** [comment]
@Treverr Aquadoor mainly. We could eventually do Type of Winter Cover, but the more I think about this the more redundant it seems. Our employees should know what an Aquadoor is, and if they don't they're not doing their jobs right.
