### ISSUE TITLE
Chemical Checkout Screen

### ISSUE THREAD

**Issue by Treverr** [Treverr/inSparkle#34]

**Comment by Treverr** [comment]
Need to design a mockup of how the screen should look and function.

**Comment by rcasad** [comment]
![image](https://cloud.githubusercontent.com/assets/16257933/12901135/ef1aed8e-ce87-11e5-94d9-4387d66cec4f.jpeg)

**Comment by Treverr** [comment]
Can you find a Cart icon you like please :) @rcasad

**Comment by rcasad** [comment]
[Shopping Cart.zip](https://github.com/Treverr/inSparkle/files/127403/Shopping.Cart.zip)

**Comment by rcasad** [comment]
Algaecide 30
Algaecide 60
Algicil 
QLF Algaecide
Stain & Scale Control
Stain-X
Ascorb-X
5lb 3" Chlorine Tablets
10lb 3" Chlorine Tablets
25lb 3" Chlorine Tablets
50lb 3" Chlorine Tablets
5lb 1" Chlorine Tablets
10lb 1" Chlorine Tablets
25lb 1" Chlorine Tablets
1 Gallon Liquid Chlorine
1 Case Liquid Chlorine
1 Gallon Muriatic Acid
1 Case Muriactic Acid
40lb Salt
50lb Sand
2lb Chlorine Stabilizer
4lb Chlorine Stabilizer
Diamond Blue
Majestic Blue
Hydro-Floc
Alum
CULator
1lb Quick Shock
5lb Rapid Shock
10lb Rapid Shock
25lb Rapid Shock
5lb Chlorinating Granules
10lb Chlorinating Granules
25lb Chlorinating Granules
50lb Chlorinating Granules
2.5lb pH Rise
5lb pH Rise
9lb pH Rise
25lb pH Rise
50lb pH Rise
3lb pH Lower
6lb pH Lower
5lb Alkalinity Rise
9lb Alkalinity Rise
25lb Alkalinity Rise
Novatrol
Algae Hunter
Phos-X
10lb DE (Earth)
25lb DE (Earth)
50lb DE (Earth)
PoolRx (Blue)
PoolRx (Black)
2lb Pepper
Crystal Cube

**Comment by rcasad** [comment]
Colors:

Algaecide 30 - 0,136,255
Algicil - 0,0,0
QLF Algaecide - 255,105,180
Stain & Scale Control - 210,105,30
Stain-X - 139,69,19
Ascorb-X - 0,0,255
5lb 3" Chlorine Tablets - 201,66,66
10lb 3" Chlorine Tablets - 201,66,66
25lb 3" Chlorine Tablets - 201,66,66
50lb 3" Chlorine Tablets - 201,66,66
5lb 1" Chlorine Tablets - 0,0,255
10lb 1" Chlorine Tablets - 0,0,255
25lb 1" Chlorine Tablets - 0,0,255
1 Gallon Liquid Chlorine - 178,255,102
1 Case Liquid Chlorine - 178,255,102
1 Gallon Muriatic Acid - 255,0,0
1 Case Muriactic Acid - 255,0,0
40lb Salt - 255,255,255
50lb Sand - 240,230,140
2lb Chlorine Stabilizer - 50,205,50
4lb Chlorine Stabilizer - 50,205,50
Diamond Blue - 0,0,255
Majestic Blue - 0,0,255
Hydro-Floc - 255,0,0
Alum - 
CULator - 
1lb Quick Shock - 255,255,0
5lb Rapid Shock - 0,0,255
10lb Rapid Shock - 0,0,255
25lb Rapid Shock - 0,0,255
5lb Chlorinating Granules - 255,20,147
10lb Chlorinating Granules - 255,20,147
25lb Chlorinating Granules - 255,20,147
50lb Chlorinating Granules - 255,20,147
2.5lb pH Rise - 255,140,0
5lb pH Rise - 255,140,0
9lb pH Rise - 255,140,0
25lb pH Rise - 255,140,0
50lb pH Rise - 255,140,0
3lb pH Lower 139,0,139
6lb pH Lower - 139,0,139
5lb Alkalinity Rise - 64,224,208
9lb Alkalinity Rise - 64,224,208
25lb Alkalinity Rise - 64,224,208
Novatrol - 250,128,114
Algae Hunter - 255,215,0
Phos-X - 32,178,170
10lb DE (Earth) - 255,255,255
25lb DE (Earth) - 255,255,255
50lb DE (Earth) - 255,255,255
PoolRx (Blue) - 0,0,255
PoolRx (Black) - 0,0,0
2lb Pepper - 0,0,0
Crystal Cube - 0,0,255

**Comment by rcasad** [comment]
Updated Cart Icoc
[Cart Icon 2.zip](https://github.com/Treverr/inSparkle/files/129404/Cart.Icon.2.zip)

**Comment by rcasad** [comment]
Algae Hunter
Algaecide 30
Algicil 
5lb Alkalinity Rise
9lb Alkalinity Rise
25lb Alkalinity Rise
Alum
Ascorb-X
5lb Chlorinating Granules
10lb Chlorinating Granules
25lb Chlorinating Granules
50lb Chlorinating Granules
2lb Chlorine Stabilizer
4lb Chlorine Stabilizer
5lb 3" Chlorine Tablets
10lb 3" Chlorine Tablets
25lb 3" Chlorine Tablets
50lb 3" Chlorine Tablets
5lb 1" Chlorine Tablets
10lb 1" Chlorine Tablets
25lb 1" Chlorine Tablets
Crystal Cube
CULator
Diamond Blue
10lb DE (Earth)
25lb DE (Earth)
50lb DE (Earth)
Hydro-Floc
1 Gallon Liquid Chlorine
1 Case Liquid Chlorine
Majestic Blue
1 Gallon Muriatic Acid
1 Case Muriatic Acid
Novatrol
2lb Pepper
3lb pH Lower
6lb pH Lower
2.5lb pH Rise
5lb pH Rise
9lb pH Rise
25lb pH Rise
50lb pH Rise
Phos-X
PoolRx (Black)
PoolRx (Blue)
QLF Algaecide
1lb Quick Shock
5lb Rapid Shock
10lb Rapid Shock
25lb Rapid Shock
40lb Salt
50lb Sand
Stain & Scale Control
Stain-X

**Comment by Treverr** [comment]
This should be complete? Correct? @rcasad

**Comment by rcasad** [comment]
Need someway to access it other than logging out.

**Comment by rcasad** [comment]
Chemical checkout looks good on iPad, but when adding two items and checking them out, generating report puts items on report twice

**Comment by rcasad** [comment]
![image](https://cloud.githubusercontent.com/assets/16257933/13340612/c1c9251e-dbff-11e5-9507-495f98c503d1.png)

**Comment by Treverr** [comment]
Resolved

![img_0109](https://cloud.githubusercontent.com/assets/5624521/13384913/96ef271a-de68-11e5-9403-7e352ceea19a.PNG)
