### ISSUE TITLE
Note Count - Message List

### ISSUE THREAD

**Issue by rbrtcsd** [Treverr/inSparkle#34]
Tom wants a count or some sort of notation on the message preview list letting you know that a particular message has notes

**Comment by Treverr** [comment]
Where exactly is he wanting this notation? Currently in the message it shows a number of notes

**Comment by rbrtcsd** [comment]
This is pointless - if the message is marked with the "other - see notes" status, we should assume there are notes, and the number of notes is irrelevant.
