### ISSUE TITLE
Multitasking/CC/Multi-Finger Gestures

### ISSUE THREAD

**Issue by rbrtcsd** [Treverr/inSparkle#7]
Are we able to shut these things off? They cause the inSparkle app to log out when one of them gets done. Mainly the multitasking sidebar and Control Center.

**Comment by Treverr** [comment]
You should be able disable this in the iPad settings itself.

Multi-tasking: Settings -> General -> Multitasking -> Allow Multiple Apps

Multi-Finger: Settings -> General -> Multitasking -> Gestures

Control Center: Settings -> Control Center -> Access Within Apps
