### ISSUE TITLE
Messages

### ISSUE THREAD

**Issue by Treverr** [Treverr/inSparkle#70]
Design / Mockup
Storyboard creation

**Comment by Treverr** [comment]
![simulator screen shot dec 23 2015 12 51 39 am](https://cloud.githubusercontent.com/assets/5624521/11971921/a378c29c-a912-11e5-91ea-cebd07632861.png)

**Comment by Treverr** [comment]
![simulator screen shot dec 23 2015 1 15 13 am](https://cloud.githubusercontent.com/assets/5624521/11971924/a697605a-a912-11e5-8b2c-1985b3fc052f.png)

**Comment by Treverr** [comment]
![simulator screen shot dec 23 2015 1 19 25 am](https://cloud.githubusercontent.com/assets/5624521/11971961/3739bae0-a913-11e5-9ed4-98383f7d2469.png)

**Comment by Treverr** [comment]
![simulator screen shot dec 23 2015 1 21 16 am](https://cloud.githubusercontent.com/assets/5624521/11971980/7dca4d1c-a913-11e5-8c56-e0d9a0eb7ed6.png)

@rcasad comment with Approval of design

**Comment by rcasad** [comment]
Dot is too big. Names and date not aligned.

**Comment by Treverr** [comment]
Updated. Added Time of status update.
![simulator screen shot dec 23 2015 10 44 21 pm](https://cloud.githubusercontent.com/assets/5624521/11989163/ba0af4ee-a9c6-11e5-956c-4466ee0cc70a.png)

**Comment by Treverr** [comment]
![simulator screen shot dec 27 2015 11 49 37 pm](https://cloud.githubusercontent.com/assets/5624521/12014164/8907eb5a-acf4-11e5-9d6b-9ce6348cc804.png)

**Comment by Treverr** [comment]
@rcasad Mock up 1 design.

**Comment by Treverr** [comment]
![simulator screen shot dec 29 2015 4 14 38 pm](https://cloud.githubusercontent.com/assets/5624521/12042279/4f20a7b6-ae47-11e5-8c45-1c204985e67a.png)

**Comment by Treverr** [comment]
Text Fields with Customer Look up functionality

**Comment by Treverr** [comment]
@rcasad How deep do we want this linked? To the message? Just the message list? etc.

**Comment by Treverr** [comment]
Deep Link to messages tab completed.

**Comment by Treverr** [comment]
Need to hide "Notes" for new message.
