### ISSUE TITLE
Messages Statuses

### ISSUE THREAD

**Issue by Treverr** [Treverr/inSparkle#76]
List of status for Messages please.

**Comment by rcasad** [comment]
Unread - before recipient has opened message, 
Left Message - when recipient calls customer back and leaves a message 
Line Busy - when recipient returns customer call but line is busy
No Answer/No Voicemail - when recipient returns call but receives no answer from customer and no voicemail picks up 
Wrong Number - when recipient returns call but gets a wrong number (could possibly alert the user that entered the message? to go correct their error?) 
Responded - when recipient returns call and talks to customer (could possibly then prompt for notes about the call? additional information learned?)

**Comment by rcasad** [comment]
Also, we might want to be able to create a work order directly from  the messages screen: like a little (...) in the upper right that makes a drop down, one of the options being "Create Work Order" and that would send the customers information immediately to the Work Order screen, with the notes from the message in the "notes" section of the work order.

**Comment by Treverr** [comment]
Change status to "Read" and set Unread to false

**Comment by Treverr** [comment]
^^ Completed
