### ISSUE TITLE
iOS 10 Updates

### ISSUE THREAD

**Issue by Treverr** [Treverr/inSparkle#8]
Can you please update all ISU (In-Store Use) devices to iOS 10.0.1 GM release?

I have all downloads on the sever and shared for the iPad's and iPhone's. I am preparing to update the app to require iOS 10 here soon.

Thank you :)

**Comment by rbrtcsd** [comment]
Cant use ISU as an abbreviation, thats our university remember. 

Downloading IPSWs now, expect to be updated by 1700 EST. 

You're welcome. 😊
