### ISSUE TITLE
Statuses

### ISSUE THREAD

**Issue by rcasad** [Treverr/inSparkle#80]
Please add two new issues:
-Completed
-Other (See Notes)

Icons are attached. 
[Other.zip](https://github.com/Treverr/inSparkle/files/116210/Other.zip)
[Completed.zip](https://github.com/Treverr/inSparkle/files/116211/Completed.zip)

**Comment by Treverr** [comment]
![simulator screen shot feb 3 2016 10 06 03 pm](https://cloud.githubusercontent.com/assets/5624521/12804562/56c451e2-cac2-11e5-9527-2fd3708aaeba.png)
