### ISSUE TITLE
Customer Updates

### ISSUE THREAD

**Issue by rcasad** [Treverr/inSparkle#89]
When updating phone number for customers, account number should change as well. 

Email sent to Robert specifying what changes to make should include OLD account number.

**Comment by Treverr** [comment]
This will be included with the next update, the format will be: 

Account Number: 1234567 -> 7654321

**Comment by Treverr** [comment]
Tested, please confirm.

**Comment by rcasad** [comment]
Please add space between both numbers and arrow.

**Comment by Treverr** [comment]
Done.
