### ISSUE TITLE
Work Order Statuses

### ISSUE THREAD

**Issue by rcasad** [Treverr/inSparkle#96]
-After completed, we need a status to mark it as "Billed" to let us know that the customer has been billed. 
-Need button to dismiss work order status screen
-Tom would like the icon from the W/O statuses to be on the main list of work orders, next to the word (new, in progress, etc.)

**Comment by Treverr** [comment]
Completed.

**Comment by Treverr** [comment]
Dismiss button added. Archiving now.

**Comment by Treverr** [comment]
Update has been pushed.
